config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'posts#index'
  resources :posts do
    collection do
      get 'inquiry'
      get 'reports'
    end
  end

  resources :items do
    collection do
      get 'purchase'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  has_many_attached :images
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  # before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  
  def index 
  end

  def purchase
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
  end
  
  def new
    @post = Post.new
  end

  def create
    @post = Post.create params.require(:post).permit(:title, :comment, images: [])
    redirect_to @post
  end

  def show
    @post = Post.find(params[:id])
    # @post = Post.where()
  end

  def inquiry
  end

  def reports
  end

  # private
  #   # paramsから欲しいデータのみ抽出
  #   def post_params
  #     params.require(:post).permit(:title, :comment, images: [])
  #   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
  
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/items/purchase.html.haml
.purchase-container
  .purchase-container__central-images
    .purchase-container__central-images__background
      %h1.purchase-container__central-images__background--text-l 
        購入確認画面
      %p.purchase-container__central-images__background--text-s  
        よろしければ購入ボタンを押してください。
    .purchase-container__central-images__item-list
      = link_to "商品一覧に戻る", items_path
    = image_tag "common/background-image3.png", class: "purchase-container__central-images__slide-image"
  .purchase-container__items-box
    .purchase-container__items-box__purchase-item
    .purchase-container__items-box__display 
      %h4 合計
      .purchase-container__items-box__display--total-price
        %h4 ¥ 5,000
    .purchase-container__items-box__purchase-btn
      = link_to "購入", ""

app/views/layouts/application.html.haml
!!!
%html 
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title OriginalApp Surfing
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    %link{:href => "https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/themes/base/jquery-ui.min.css", :rel => "stylesheet"}/
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %script{:src => "https://cdnjs.cloudflare.com/ajax/libs/jquery.ripples/0.5.3/jquery.ripples.min.js"}
    %script{:src => "https://ajax.googleapis.com/ajax/libs/jqueryui/1/jquery-ui.min.js"}
    %script{:src => "https://ajax.googleapis.com/ajax/libs/jqueryui/1/i18n/jquery.ui.datepicker-ja.min.js"}
   
  %body
    = yield

app/views/posts/_side-navi.html.haml
.side-bar
  .side-bar__inner
    .side-bar__inner__navi
      = icon('fas', 'bars', class: 'side-bar__inner__navi--open-icon')
    %ul.side-bar__inner__menu 
      %li.side-bar__inner__menu--list 
        = link_to "HOME", root_path
      %li.side-bar__inner__menu--list
        = link_to "EVERY POST", ""
      - if user_signed_in?
        %li.side-bar__inner__menu--list
          = link_to "NEW POST", new_post_path
        %li.side-bar__inner__menu--list
          = link_to "LOG OUT", destroy_user_session_path, method: :delete
      - else
        %li.side-bar__inner__menu--list
          = link_to "NEW ACOUNT", new_user_registration_path
        %li.side-bar__inner__menu--list
          = link_to "LOG IN", new_user_session_path
      %li.side-bar__inner__menu--list
        = link_to "ITEM LIST", items_path
      %li.side-bar__inner__menu--list
        = link_to "NEWS & WEATHER", reports_posts_path
      %li.side-bar__inner__menu--list
        = link_to "Q&A", inquiry_posts_path
      .side-bar__inner__close
        = icon('fas', 'times', class: 'side-bar__inner__close--icon')

app/views/posts/index.html.haml
.wrapper
  = render "side-navi.html.haml"

  .main-content
    .main-content__ripple
    .main-content__app-title
      %span{data: {name: 'Surfing'}} Surfing
      %p マリンスポーツのECサイト

app/views/posts/inquiry.html.haml
.wrapper
  = render "side-navi.html.haml"

  .main-section
    %h2 問い合わせ
    .main-section__form
      %h3 よくある質問
      .main-section__form--question
        Q1 どのようなAppですか？
      .main-section__form--answer
        回答内容は準備中です
      .main-section__form--question
        Q2 クレジットカードでの支払いは可能ですか？
      .main-section__form--answer
        回答内容は準備中です
      .main-section__form--question
        Q3 今後、追加したい機能はありますか？
      .main-section__form--answer
        回答内容は準備中です

  .moving-surfing
    = image_tag "common/moving-surfing.image.png", class: "moving-surfing--image"

app/views/posts/new.html.haml
.wrapper
  = render "side-navi.html.haml"
= form_with model: @post, local: true  do |post|
  .main-cotents
    -# 画像投稿セクション
    .main-cotents__post-images
      .main-cotents__post-images__drop-box
        %h2 投稿する画像を選択してください
        .main-cotents__post-images__drop-box__select-image
          = post.file_field :images, class: "main-cotents__post-images__drop-box__select-image--file_field", multiple: true
          = post.submit 'New Post', class: "main-cotents__post-images__drop-box__select-image--submit"

      .main-cotents__post-images--notice
        %p ・同時に複数枚の画像が投稿できます
        %p ・不適切な投稿はやめましょう

    -# 本人ユーザーの投稿へのタイトル、カテゴリー、コメント
    .main-cotents__post-container
      .main-cotents__post-container__title
        = post.label 'タイトル'
        = post.text_field :title, placeholder: " 投稿する写真にタイトルをつけよう", class: "main-cotents__post-container__title--form"
        %p 不適切な投稿はやめましょう
      .main-cotents__post-container__category
        %h2 カテゴリー 
        %p カテゴリーを選択してください
        .main-cotents__post-container__category--option
          = post.select :category, {"ボード": :category_1,'メンズ水着': :category_2,'レディース水着': :category_3,'その他': :category_4 }, id: "post_category"
      .main-cotents__post-container__comment
        = post.label 'コメント'
        = post.text_area :comment, placeholder: " 投稿する写真にコメントをつけよう", class: "main-cotents__post-container__comment--form"

app/views/posts/reports.html.haml
.wrapper
  = render "side-navi.html.haml"

  .contents-box
    .contents-box__top-content
      %h2 Weather 
      .contents-box__top-content__weather
        .contents-box__top-content__weather--city-name
          #city-name
        #weather.contents-box__top-content__weather__lists
          .contents-box__top-content__weather__lists__weather-report

    .contents-box__main-contents
      .contents-box__main-contents__left-contents
        %h2 Report
        .contents-box__main-contents__left-contents__report
          .contents-box__main-contents__left-contents__report--image
            = image_tag "common/ori-app.sample1.png"
          .contents-box__main-contents__left-contents__report__content
            .contents-box__main-contents__left-contents__report__content--title
              %span 記事のタイトル
            .contents-box__main-contents__left-contents__report__content--article
              %span 記事の内容は準備中です。記事の内容は準備中です。記事の内容は準備中です。記事の内容は準備中です。記事の内容は準備中です。記事の内容は準備中です。記事の内容は準備中です。記事の内容は準備中です。
        
        .contents-box__main-contents__left-contents__report
          .contents-box__main-contents__left-contents__report--image
            = image_tag "common/ori-app.sample1.png"
          .contents-box__main-contents__left-contents__report__content
            .contents-box__main-contents__left-contents__report__content--title
              %span 記事のタイトル
            .contents-box__main-contents__left-contents__report__content--article
              %span 記事の内容は準備中です。記事の内容は準備中です。記事の内容は準備中です。記事の内容は準備中です。記事の内容は準備中です。記事の内容は準備中です。記事の内容は準備中です。記事の内容は準備中です。記事の内容は準備中です記事の内容は準備中です記事の内容は準備中です記事の内容は準備中です記事の内容は準備中です記事の内容は準備中です
        
        .contents-box__main-contents__left-contents__report
          .contents-box__main-contents__left-contents__report--image
            = image_tag "common/ori-app.sample1.png"
          .contents-box__main-contents__left-contents__report__content
            .contents-box__main-contents__left-contents__report__content--title
              %span 記事のタイトル
            .contents-box__main-contents__left-contents__report__content--article
              %span 記事の内容は準備中です。記事の内容は準備中です。記事の内容は準備中です。記事の内容は準備中です。記事の内容は準備中です。記事の内容は準備中です。記事の内容は準備中です。記事の内容は準備中です。
        
        .contents-box__main-contents__left-contents__report
          .contents-box__main-contents__left-contents__report--image
            = image_tag "common/ori-app.sample1.png"
          .contents-box__main-contents__left-contents__report__content
            .contents-box__main-contents__left-contents__report__content--title
              %span 記事のタイトル
            .contents-box__main-contents__left-contents__report__content--article
              %span 記事の内容は準備中です。記事の内容は準備中です。記事の内容は準備中です。記事の内容は準備中です。記事の内容は準備中です。記事の内容は準備中です。記事の内容は準備中です。記事の内容は準備中です。
        
        .contents-box__main-contents__left-contents__report
          .contents-box__main-contents__left-contents__report--image
            = image_tag "common/ori-app.sample1.png"
          .contents-box__main-contents__left-contents__report__content
            .contents-box__main-contents__left-contents__report__content--title
              %span 記事のタイトル
            .contents-box__main-contents__left-contents__report__content--article
              %span 記事の内容は準備中です。記事の内容は準備中です。記事の内容は準備中です。記事の内容は準備中です。記事の内容は準備中です。記事の内容は準備中です。記事の内容は準備中です。記事の内容は準備中です。
        
      .contents-box__main-contents__right-contents
        %h2 Calender
        #datepicker.contents-box__main-contents__right-contents--calender
        
      

app/views/posts/show.html.haml
- @post.images.each do |image| 
  = image_tag image